//! XMP sidecar writer — render an [`EditRecipe`] as an Adobe Camera Raw /
//! Lightroom `.xmp` sidecar (the `crs:` namespace), so the AI's edit opens as
//! adjustable develop sliders in the user's catalog.
//!
//! Key names, value conventions, and structure were verified against a real ACR
//! sidecar from the user's own library (`DSC08724.xmp`): `ProcessVersion=15.4`,
//! signed-integer sliders, `Sharpness` on 0..100, tone curve as an `rdf:Seq` of
//! `"x, y"` strings (see `docs/M1_PLAN.md` §5 and §9). We emit only the keys we
//! set; Lightroom fills the rest from defaults.

use crate::recipe::EditRecipe;

/// Format an integer-valued slider the way ACR writes it: explicit `+` for
/// positives (`"+14"`, `"-12"`, `"0"`).
fn signed(v: f32) -> String {
    let i = v.round() as i64;
    if i > 0 {
        format!("+{i}")
    } else {
        i.to_string()
    }
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn attr(buf: &mut String, key: &str, val: &str) {
    buf.push_str(&format!("\n    crs:{key}=\"{val}\""));
}

/// Render `recipe` as a complete `.xmp` sidecar document.
pub fn recipe_to_xmp(r: &EditRecipe) -> String {
    let mut a = String::new();

    // ProcessVersion 15.4 / Version 15.5.1 are the verified current values from
    // the user's real sidecar (not the research's guessed 11.0/15.0).
    attr(&mut a, "Version", "15.5.1");
    attr(&mut a, "ProcessVersion", "15.4");

    // White balance: an explicit temperature means Custom WB; otherwise leave
    // it As Shot and only carry a tint if non-neutral.
    if let Some(k) = r.temperature_k {
        attr(&mut a, "WhiteBalance", "Custom");
        attr(&mut a, "Temperature", &(k.round() as i64).to_string());
        attr(&mut a, "Tint", &signed(r.tint));
    } else {
        attr(&mut a, "WhiteBalance", "As Shot");
        if r.tint != 0.0 {
            attr(&mut a, "Tint", &signed(r.tint));
        }
    }

    // Exposure as a plain decimal (Lightroom parses signed or unsigned).
    attr(&mut a, "Exposure2012", &format!("{:.2}", r.exposure_ev));
    attr(&mut a, "Contrast2012", &signed(r.contrast));
    attr(&mut a, "Highlights2012", &signed(r.highlights));
    attr(&mut a, "Shadows2012", &signed(r.shadows));
    attr(&mut a, "Whites2012", &signed(r.whites));
    attr(&mut a, "Blacks2012", &signed(r.blacks));
    attr(&mut a, "Clarity2012", &signed(r.clarity));
    attr(&mut a, "Dehaze", &signed(r.dehaze));
    attr(&mut a, "Vibrance", &signed(r.vibrance));
    attr(&mut a, "Saturation", &signed(r.saturation));

    // recipe sharpening is 0..150; crs Sharpness is 0..100 — rescale + clamp.
    let sharp = ((r.sharpening * 2.0 / 3.0).round() as i64).clamp(0, 100);
    attr(&mut a, "Sharpness", &sharp.to_string());
    let nr = (r.noise_reduction.round() as i64).clamp(0, 100);
    attr(&mut a, "LuminanceSmoothing", &nr.to_string());

    // Crop (normalised [0,1]); only applied by Lightroom when HasCrop is True.
    if let Some(c) = &r.crop {
        attr(&mut a, "HasCrop", "True");
        attr(&mut a, "CropTop", &format!("{:.6}", c.top));
        attr(&mut a, "CropLeft", &format!("{:.6}", c.left));
        attr(&mut a, "CropBottom", &format!("{:.6}", c.bottom));
        attr(&mut a, "CropRight", &format!("{:.6}", c.right));
    } else {
        attr(&mut a, "HasCrop", "False");
    }
    if r.straighten_deg != 0.0 {
        attr(&mut a, "CropAngle", &format!("{:.1}", r.straighten_deg));
    }

    attr(
        &mut a,
        "ToneCurveName2012",
        if r.tone_curve.is_empty() { "Linear" } else { "Custom" },
    );

    // Tone curve is a child element (rdf:Seq of "x, y" strings), not an attribute.
    let tone = if r.tone_curve.is_empty() {
        String::new()
    } else {
        let pts: String = r
            .tone_curve
            .iter()
            .map(|p| format!("     <rdf:li>{}, {}</rdf:li>\n", p.input, p.output))
            .collect();
        format!(
            "\n   <crs:ToneCurvePV2012>\n    <rdf:Seq>\n{pts}    </rdf:Seq>\n   </crs:ToneCurvePV2012>"
        )
    };

    format!(
        "<x:xmpmeta xmlns:x=\"adobe:ns:meta/\" x:xmptk=\"Autoshop\">\n\
 <!-- Generated by Autoshop. AI rationale: {rationale} (confidence {conf:.2}) -->\n\
 <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n\
  <rdf:Description rdf:about=\"\"\n\
    xmlns:crs=\"http://ns.adobe.com/camera-raw-settings/1.0/\"{attrs}\n\
    crs:HasSettings=\"True\">{tone}\n\
  </rdf:Description>\n\
 </rdf:RDF>\n\
</x:xmpmeta>\n",
        rationale = xml_escape(&r.rationale),
        conf = r.confidence,
        attrs = a,
        tone = tone,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::recipe::{CurvePoint, EditRecipe};

    #[test]
    fn renders_expected_crs_keys() {
        let r = EditRecipe {
            exposure_ev: 0.32,
            contrast: 14.0,
            highlights: -12.0,
            temperature_k: Some(5600.0),
            tint: 3.0,
            sharpening: 45.0, // -> Sharpness 30
            tone_curve: vec![
                CurvePoint { input: 0, output: 0 },
                CurvePoint { input: 255, output: 255 },
            ],
            rationale: "warm & contrasty <test> & \"q\"".into(),
            confidence: 0.82,
            ..Default::default()
        };
        let xmp = recipe_to_xmp(&r);
        assert!(xmp.contains(r#"crs:ProcessVersion="15.4""#));
        assert!(xmp.contains(r#"crs:Exposure2012="0.32""#));
        assert!(xmp.contains(r#"crs:Contrast2012="+14""#));
        assert!(xmp.contains(r#"crs:Highlights2012="-12""#));
        assert!(xmp.contains(r#"crs:WhiteBalance="Custom""#));
        assert!(xmp.contains(r#"crs:Temperature="5600""#));
        assert!(xmp.contains(r#"crs:Sharpness="30""#)); // 45 * 2/3
        assert!(xmp.contains("<crs:ToneCurvePV2012>"));
        assert!(xmp.contains("<rdf:li>0, 0</rdf:li>"));
        // rationale is XML-escaped in the comment
        assert!(xmp.contains("&lt;test&gt;"));
    }
}
